import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Dashboard",
  description: "Generated by Dev Omar Abdallah",
};
export default function RootLayout({ children }) {

  if (process.env.NODE_ENV === "development") {
  console.error = () => {};
};

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} `}
      >
        {children}
      </body>
    </html>
  );
};